version: "3.9"
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
      SECRET_KEY: "your-secret-key"
      DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1 [::1]"
      POSTGRES_USER: "django"
      POSTGRES_PASSWORD: "django"
      POSTGRES_DB: "django_db"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "django"
      POSTGRES_PASSWORD: "django"
      POSTGRES_DB: "django_db"
    ports:
      - "5432:5432"

volumes:
  postgres_data:
