apiVersion: v1
kind: Service
metadata:
  name: django
spec:
  type: LoadBalancer
  ports:
    - port: 8000
  selector:
    app: django
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: app-web:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_DB
              value: django_db
            - name: POSTGRES_USER
              value: django
            - name: POSTGRES_PASSWORD
              value: django
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
          volumeMounts:
            - name: static-files
              mountPath: /app/staticfiles
            - name: media-files
              mountPath: /app/media
      volumes:
        - name: static-files
          emptyDir: {}
        - name: media-files
          emptyDir: {}
